title: "Internal Audit & Analytics Portfolio"
logo: "/assets/img/profile_circle.png"
description: >
  <strong>Colby Kellersberger, CIA, CFE, CICA</strong><br><br>

  <a href="https://linkedin.com/in/colby-k" target="_blank" style="text-decoration: none;">
    <img src="/assets/icons/LinkedIn.svg" width="28" title="LinkedIn" style="margin-right: 6px;">
  </a>
  <a href="https://github.com/colby-k" target="_blank" style="text-decoration: none;">
    <img src="/assets/icons/github.svg" width="28" title="GitHub">
  </a>
    
favicon: "/portfolio.ico"

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown

url: "https://colby-k.github.io"
baseurl: ""
